# Generated by Django 3.0.3 on 2020-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
