# Generated by Django 3.0.3 on 2020-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelens',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
