# Generated by Django 3.0.3 on 2020-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLens', '0002_imagelens_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelens',
            name='name',
            field=models.CharField(default='Main_Img.jpg', editable=False, max_length=12),
        ),
    ]
