# Generated by Django 3.0.3 on 2020-06-20 20:26

import MyLens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLens', '0005_auto_20200620_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelens',
            name='Main_Img',
            field=models.ImageField(upload_to=MyLens.models.path_and_rename),
        ),
    ]
