# Generated by Django 3.0.3 on 2020-06-20 20:29

import MyLens.models
import MyLens.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLens', '0006_auto_20200620_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelens',
            name='Main_Img',
            field=models.ImageField(max_length=15, storage=MyLens.storage.OverwriteStorage(), upload_to=MyLens.models.path_and_rename),
        ),
    ]
