# Generated by Django 3.0.3 on 2020-06-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyLens', '0008_auto_20200620_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelens',
            name='name',
        ),
    ]
